version: "3.9"

services:
  web:
    image: c270_app
    ports:
      - "8080:3000"  # Map host port 8080 to container port 3000
    deploy:
      replicas: 2  # Number of replicas for load balancing.
      placement:
        constraints:
          - node.role == manager
