name: C270 CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo 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 | docker login -u Dhiveyasree --password-stdin

      - name: Build Docker image
        run: docker build . -t your-image-name

      - name: Push Docker image
        run: docker push your-image-name
